# Generated by Django 4.1.7 on 2023-04-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_qr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qr',
        ),
    ]
