# Generated by Django 4.1.7 on 2023-04-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_delete_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qr/')),
            ],
        ),
        migrations.DeleteModel(
            name='Oracion',
        ),
    ]
